# WhatsApp Notifier Agent Configuration
# Dedicated agent for MCP WhatsApp integration

agent:
  agent_id: "whatsapp-notifier"
  version: 1
  name: "WhatsApp Notifier"
  role: "WhatsApp Notification Specialist"
  description: "Sends WhatsApp notifications using MCP tools for customer escalations"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.3
  max_tokens: 1000

instructions: |
  You are a WhatsApp notification specialist for PagBank.
  
  Your function is to:
  - Send WhatsApp notifications via MCP tools
  - Format messages clearly and professionally
  - Handle escalation notifications to support teams
  - Ensure message delivery confirmation
  
  Always:
  - Use clear, professional Portuguese
  - Include protocol IDs and timestamps
  - Format messages for mobile readability
  - Confirm successful delivery
  
  Environment requirements:
  - EVOLUTION_API_BASE_URL
  - EVOLUTION_API_API_KEY
  - EVOLUTION_API_INSTANCE
  - EVOLUTION_API_FIXED_RECIPIENT (optional)

# MCP Tools configuration
# Note: In production, this would include:
# tools:
#   - mcp_tools: 
#       server: "mcp-server-whatsapp"
#       functions: ["send_text_message", "send_media", "send_presence"]
# For now, MCP integration is handled in the agent code

# Storage configuration
storage:
  type: "postgres"
  table_name: "whatsapp_notifier"
  auto_upgrade_schema: true

# Memory settings
memory:
  add_history_to_messages: false  # Notifications don't need history
  num_history_runs: 1

# Display settings
markdown: false
show_tool_calls: true

# WhatsApp specific configuration
whatsapp:
  default_instance: "pagbank_support"
  default_delay: 1200  # milliseconds
  
# Notification templates
notification_templates:
  escalation: |
    🚨 *Escalação PagBank*
    
    📋 *Protocolo:* {protocol_id}
    👤 *Cliente:* {customer_name}
    ⚠️ *Urgência:* {urgency}
    
    📝 *Descrição:*
    {description}
    
    🕐 *Horário:* {timestamp}
    
  high_priority: |
    🔴 *URGENTE - PagBank*
    
    📋 *Protocolo:* {protocol_id}
    ⚠️ *Situação:* {situation}
    
    📝 *Detalhes:*
    {details}
    
    🎯 *Ação Necessária:* {action_required}
    🕐 *Horário:* {timestamp}