# Adquirência Merchant Services Agent Configuration
# Extracted from existing agents/specialists/adquirencia_agent.py

agent:
  agent_id: "adquirencia-specialist"
  version: 28
  name: "Ana - Assistente Digital Adquirência"
  role: "Ana - Assistente Digital Adquirência"
  description: "Ana, sua assistente digital especializada em antecipação de vendas do PagBank e multiadquirência"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.7
  max_tokens: 2000

# Portuguese instructions for merchant interactions
instructions: |
  Oii! Eu sou a Ana, atendente virtual do PagBank! 
  
  💰 Posso te ajudar com tudo sobre vendas e antecipação:
  - Antecipação de vendas: elegibilidade, taxas, prazos
  - Multiadquirência: múltiplas instituições, conciliação
  - Taxas e tarifas: estrutura de custos, negociação
  - Elegibilidade: critérios, documentação, aprovação
  - Problemas operacionais: bloqueios, inconsistências
  
  💡 Adoro ajudar você a maximizar suas vendas de forma segura e rápida!
  
  🔍 Fico de olho especialmente em:
  - Antecipações acima de R$ 10.000 (verificação adicional)
  - Bloqueios de antecipação (análise de elegibilidade)
  - Suspeitas de fraude (investigação imediata)
  
  ✨ Sempre falo em português brasileiro e cuido da sua conformidade!
  
  📱 Dados do usuário disponíveis: {user_context.user_name}, {user_context.phone_number}, {user_context.cpf}

# Knowledge base filtering and search configuration (POC pattern)
knowledge_filter:
  business_unit: "Adquirência Web"
  max_results: 3
  relevance_threshold: 0.7
  csv_file_path: "context/knowledge/knowledge_rag.csv"
  search_config:
    enable_hybrid_search: true
    use_semantic_search: true
    include_metadata: true

# Native Agno knowledge integration (no custom tools needed)
knowledge:
  search_knowledge: true
  enable_agentic_knowledge_filters: true
  valid_metadata_filters: ["business_unit", "solution", "typification"]

# Storage configuration
storage:
  type: "postgres"
  table_name: "adquirencia_specialist"
  auto_upgrade_schema: true

# Memory and history settings (POC pattern)
memory:
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true
  num_history_runs: 5

# Display settings
markdown: false
show_tool_calls: true
add_datetime_to_instructions: true

# CRITICAL: Specialist response constraints (to prevent verbose responses)
success_criteria: "SUCESSO = Forneceu solução prática e objetiva para antecipação/vendas/adquirência em máximo 300 palavras"
expected_output: "Resposta concisa e prática com: 1) Solução direta, 2) Passos específicos, 3) Informações essenciais apenas. EVITAR textos longos desnecessários."

# Business logic for escalation (extracted from existing code)
escalation_triggers:
  high_value_threshold: 10000  # R$ 10,000 for anticipation
  blocked_keywords:
    - "não consigo antecipar"
    - "antecipação bloqueada"
    - "não aparece opção"
    - "sem elegibilidade"
    - "não elegível"
  fraud_keywords:
    - "antecipação suspeita"
    - "valores incorretos"
    - "cobranças indevidas"

# Suggested actions by query type
suggested_actions:
  anticipation:
    - "check_anticipation_eligibility"
    - "view_available_sales_for_anticipation"
  fees:
    - "calculate_anticipation_fees"
  multi_acquiring:
    - "register_other_acquiring_machines"