# Simplified Docker Compose for PagBank Multi-Agent System
# Essential services only: App + PostgreSQL

version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION:-latest}
        BUILD_DATE: ${BUILD_DATE}
        GIT_SHA: ${GIT_SHA}
    container_name: pagbank-agents
    restart: unless-stopped
    ports:
      - "${PB_AGENTS_PORT:-7777}:${PB_AGENTS_PORT:-7777}"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-pagbank123}@postgres:5432/pagbank_agents
      - RUNTIME_ENV=prd
      - LOG_LEVEL=info
      - PB_AGENTS_PORT=${PB_AGENTS_PORT:-7777}
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PB_AGENTS_PORT:-7777}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PostgreSQL database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pagbank-pgvector
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pagbank_agents
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pagbank123}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

# Network configuration
networks:
  app_network:
    driver: bridge

# Persistent volumes
volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local
  app_data:
    driver: local