[project]
name = "genie-agents"
version = "0.1.0"
description = "Automagik Multi-Agent Framework - Extensible Agent Creation System"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.0",
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.29.0",
    "anthropic>=0.31.0",
    "sentence-transformers>=2.2.0",
    "pgvector>=0.2.0",
    "pandas>=2.0.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "rich>=13.0.0",
    "aiofiles>=24.1.0",
    "openai>=1.93.2",
    "cohere>=5.15.0",
    "psycopg[binary]>=3.2.9",
    "sqlalchemy>=2.0.0",
    "fastapi>=0.116.0",
    "uvicorn>=0.35.0",
    "mcp>=1.10.1",
    "httpx>=0.28.1",
    "watchdog>=6.0.0",
    "psutil>=5.9.0",
    "numpy>=1.24.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "alembic>=1.16.4",
    "aiohttp>=3.12.14",
    "pyyaml>=6.0.2",
    "gitpython>=3.1.44",
    "requests>=2.32.4",
    "pytest-benchmark>=5.1.0",
    "memory-profiler>=0.61.0",
    "line-profiler>=4.2.0",
    "scipy>=1.16.0",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
    "google-generativeai>=0.8.5",
    "jinja2>=3.1.6",
    "markdown>=3.8.2",
    "plotly>=6.2.0",
    "prometheus-client>=0.22.1",
    "black>=25.1.0",
    "isort>=6.0.1",
    "mypy>=1.16.1",
    "coverage>=7.9.2",
    "google-genai>=1.25.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-mock>=3.14.1",
    "pytest-cov>=6.2.1",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "pre-commit>=3.4.0",
    "pyflakes>=3.4.0",
    "isort>=5.12.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["agno.*", "anthropic.*", "sentence_transformers.*", "pgvector.*"]
ignore_missing_imports = true

[tool.setuptools]
packages = ["agents", "api", "config", "context", "utils"]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["agno", "automagik", "agents", "api", "config", "context", "utils"]
known_third_party = ["anthropic", "pydantic", "sqlalchemy", "fastapi", "uvicorn", "httpx", "aiohttp", "pandas", "numpy", "sentence_transformers", "pgvector", "rich", "typer", "pytest", "openai", "cohere"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "E501", "W503"]
exclude = [".venv", "__pycache__", ".git", "*.egg-info"]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "isort>=6.0.1",
    "mypy>=1.16.1",
    "ruff>=0.12.3",
]
