agent:
  name: "AGNO Native Context Example"
  role: "Personalized Assistant"
  version: dev
  agent_id: template-example
  description: >
    Dynamic agent configured with AGNO native context capabilities.
    Demonstrates context-aware personalization for organizations.

model:
  id: claude-sonnet-4-20250514
  provider: anthropic
  max_tokens: 2000
  temperature: 0.1

# AGNO native context - automatically injected
add_context: true
resolve_context: true

memory:
  num_history_runs: 5
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true

storage:
  type: postgres
  table_name: agents_template_example
  auto_upgrade_schema: true

markdown: false

knowledge:
  search_knowledge: true
  valid_metadata_filters:
  - business_unit
  - solution
  - typification
  enable_agentic_knowledge_filters: true

instructions: |
  You are a personalized AI assistant with AGNO native context capabilities.
  
  Context will be automatically provided including:
  - User Information (name, email, phone, CPF, permissions)
  - Environment Context (environment, debug mode, timestamp)
  - Session Information (session ID, channel)
  - Organization Details (tenant name, subscription, features)
  
  Guidelines:
  - Always address users by their name when context provides it
  - Adapt responses based on environment (more formal in production)
  - Consider user's business units for specialized advice
  - Provide detailed debugging information in debug mode
  - Use available permissions to customize functionality
  - Tailor responses to subscription level and available features
  
  The context is dynamically resolved by AGNO without requiring templating.

expected_output: |
  Personalized response considering user context and preferences.
  Adapts to environment, permissions, and organizational settings.

show_tool_calls: false

knowledge_filter:
  max_results: 5
  csv_file_path: lib/knowledge/knowledge_rag.csv
  search_config:
    include_metadata: true
    use_semantic_search: true
    enable_hybrid_search: true
  relevance_threshold: 0.7

success_criteria: >
  SUCESSO = Provided personalized assistance using AGNO native context
  with context-aware responses in current environment

suggested_actions:
  general:
  - get_help
  - contact_support
  - view_profile
  - update_preferences

escalation_triggers:
  error_keywords:
  - critical error
  - system failure
  - data loss

add_datetime_to_instructions: true

# Context configuration for AGNO native context
context_config:
  enable_user_context: true
  enable_session_context: true
  enable_system_context: true
  enable_tenant_context: true
  personalization_level: "high"
  user_segment: "general"