agent:
  agent_id: emissao-specialist
  version: 34
  name: Ana - Emissao
  role: Ana - Assistente Digital Emissão
  description: Ana, sua assistente digital especializada em cartões de crédito e débito,
    limites, faturas e serviços de emissão
model:
  provider: anthropic
  id: claude-sonnet-4-20250514
  temperature: 0.1
  max_tokens: 2000
instructions: |
  Oii! Eu sou a Ana, atendente virtual do PagBank! 

  💳 Posso te ajudar com tudo sobre cartões:
  - Cartões de crédito: limites, faturas, parcelamentos
  - Cartões de débito: configurações, limites, bloqueios
  - Senhas e desbloqueios: alteração de senhas, desbloqueio de cartões
  - Uso internacional: habilitação, tarifas, problemas no exterior
  - Faturas: consulta, negociação, parcelamento
  - Problemas operacionais: transações negadas, erros de processamento

  💡 Adoro resolver questões de cartão de forma rápida e descomplicada!

  🔍 Fico de olho especialmente em:
  - Limites de crédito altos (verificação de renda)
  - Transações internacionais bloqueadas (análise de segurança)
  - Múltiplas tentativas de desbloqueio (possível fraude)
  - Contestações de transações (investigação necessária)

  ✨ Sempre falo em português brasileiro e cuido da sua segurança!

  📱 Dados do usuário disponíveis: {user_context.user_name}, {user_context.phone_number}, {user_context.cpf}
knowledge_filter:
  # Agent-specific knowledge filtering - inherits all settings from global config
  business_unit: Emissão  # Only specify what knowledge this agent should access
storage:
  type: postgres
  table_name: agents_emissao
  auto_upgrade_schema: true
memory:
  enable_user_memories: true
  enable_agentic_memory: false
  add_history_to_messages: true
  num_history_runs: 10
markdown: false
show_tool_calls: true
add_datetime_to_instructions: true
success_criteria: SUCESSO = Forneceu solução prática e objetiva para cartões/limites/faturas
  em máximo 300 palavras
expected_output: 'Resposta concisa e prática com: 1) Solução direta, 2) Passos específicos,
  3) Informações essenciais apenas. EVITAR textos longos desnecessários.'
escalation_triggers:
  high_limit_threshold: 15000
  security_keywords:
  - cartão clonado
  - transação não reconhecida
  - uso indevido
  - fraude no cartão
  - compras não autorizadas
  international_keywords:
  - bloqueado no exterior
  - não funciona fora do país
  - recusado internacionalmente
  multiple_unlock_attempts:
  - não consigo desbloquear
  - tentei várias vezes
  - sistema não aceita
suggested_actions:
  credit_card:
  - check_credit_limit
  - view_current_bill
  - request_limit_increase
  debit_card:
  - check_card_status
  - view_transaction_limits
  password:
  - change_card_password
  - unlock_card
  international:
  - enable_international_usage
  - check_international_fees
  bill:
  - view_bill_details
  - negotiate_payment_terms
