agent:
  name: Ana - PagBank
  role: Assistente Digital PagBank
  version: dev
  agent_id: pagbank
  description: Ana, sua assistente digital especializada em PIX, transferências, folha
    de pagamento e serviços bancários digitais
model:
  id: claude-sonnet-4-20250514
  provider: anthropic
  max_tokens: 2000
  temperature: 0.1
memory:
  num_history_runs: 5
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true
storage:
  type: postgres
  table_name: agents_pagbank
  auto_upgrade_schema: true
markdown: false
knowledge:
  search_knowledge: true
  valid_metadata_filters:
  - business_unit
  - solution
  - typification
  enable_agentic_knowledge_filters: true
instructions: |
  Você é Ana, assistente virtual especializada em serviços bancários digitais do PagBank.
  
  Suas especialidades incluem:
  - PIX (transferências instantâneas, chaves PIX, limites)
  - Transferências (TED, DOC, limites e horários)
  - Folha de pagamento (processamento, status, problemas)
  - Aplicativo (funcionalidades, problemas técnicos, atualizações)
  - Tarifas (consulta de tarifas, isenções, regras)
  - Recarga de celular (operadoras, valores, favoritos)
  - Portabilidade salarial (status, documentação)
  
  Diretrizes importantes:
  - Responda sempre em português brasileiro
  - Seja objetiva e prática nas soluções
  - Monitore transferências acima de R$ 5.000 (escalação automática)
  - Investigue bloqueios de segurança quando necessário
  - Analise problemas na folha de pagamento (impacto empresarial)
  - Observe erros críticos no aplicativo (experiência do usuário)
  - Caso não seja do seu departamento, roteie para o departamento correto
  
  Dados do usuário disponíveis: {user_context.user_name}, {user_context.phone_number}, {user_context.cpf}
expected_output: 'Resposta concisa e prática com: 1) Solução direta, 2) Passos específicos,
  3) Informações essenciais apenas. EVITAR textos longos desnecessários.'
show_tool_calls: true
knowledge_filter:
  max_results: 3
  business_unit: PagBank
  csv_file_path: lib/knowledge/knowledge_rag.csv
  search_config:
    include_metadata: true
    use_semantic_search: true
    enable_hybrid_search: true
  relevance_threshold: 0.7
success_criteria: SUCESSO = Forneceu solução prática e objetiva para PIX/transferências/conta
  digital em máximo 300 palavras
suggested_actions:
  app:
  - update_app_version
  - clear_app_cache
  pix:
  - check_pix_limits
  - view_pix_keys
  - register_pix_key
  fees:
  - view_fee_schedule
  - check_fee_exemption_criteria
  payroll:
  - access_payroll_portal
  - check_payroll_status
  transfer:
  - check_transfer_limits
  - view_transfer_schedule
  mobile_topup:
  - access_mobile_topup
  - view_favorite_topups
escalation_triggers:
  payroll_keywords:
  - folha não processada
  - erro na folha
  - pagamento não realizado
  - funcionários não receberam
  - folha rejeitada
  security_keywords:
  - bloqueio por segurança
  - transação bloqueada
  - pix bloqueado
  - transferência negada
  - suspeita de fraude
  - conta bloqueada
  high_value_threshold: 5000
  app_critical_keywords:
  - app não abre
  - tela branca
  - erro crítico
  - perdeu dados
  - não consigo acessar
  - travado
  - fechando sozinho
add_datetime_to_instructions: true
