# Complete Agent Configuration Sample
# Based on verified Agno parameters from @genie/reference/agno-parameter-patterns.md
# Use this as template for all agent configurations

agent:
  # REQUIRED CORE IDENTITY
  agent_id: "pagbank-specialist"              # REQUIRED - Unique identifier (no version)
  version: 27                                 # Optional - Version number for API-level management
  name: "PagBank Digital Banking Expert"      # Optional - Display name
  role: "Digital banking specialist"          # Optional - Agent role description
  
  # OPTIONAL IDENTITY
  introduction: "I'm your PagBank digital banking assistant"  # Added to message history
  
model:
  # REQUIRED
  provider: "anthropic"                       # REQUIRED - Model provider
  id: "claude-sonnet-4-20250514"             # REQUIRED - Model identifier
  
  # OPTIONAL PARAMETERS
  temperature: 0.7                            # Default: None - Controls randomness
  max_tokens: 2000                            # Default: None - Maximum tokens to generate
  # api_key: "${ANTHROPIC_API_KEY}"          # Optional - Usually from environment
  # base_url: "https://api.anthropic.com"    # Optional - Custom API endpoint
  
  # CACHING (Optional)
  # cache_system_prompt: true                # Optional - Cache system prompt
  # extended_cache_time: true                # Optional - Extended cache time

# SYSTEM MESSAGE SETTINGS
system_message:
  # CUSTOM SYSTEM MESSAGE (Optional)
  # system_message: "Custom system message"  # Optional - Override default
  # system_message_role: "system"           # Default: "system"
  create_default_system_message: true        # Default: True
  
  # SYSTEM MESSAGE COMPONENTS
  description: "Expert in PagBank digital banking services"  # Added to start of system message
  # goal: "Help users with banking operations"               # Optional
  expected_output: "Clear banking guidance in Portuguese"    # Optional
  additional_context: "Always prioritize security and compliance"  # Added to end
  
  # FORMATTING INSTRUCTIONS
  markdown: false                             # Default: False - Add markdown instructions
  add_name_to_instructions: false            # Default: False
  add_datetime_to_instructions: true         # Default: False
  add_location_to_instructions: false        # Default: False

# INSTRUCTIONS (Key for agent behavior)
instructions: |
  Você é especialista em serviços bancários digitais PagBank.
  
  Suas especialidades incluem:
  - PIX: transferências instantâneas, chaves PIX, limites
  - Transferências: TED, DOC, limites e horários  
  - Conta digital: saldo, extrato, movimentações
  - Cartões: limites, faturas, desbloqueios
  
  Sempre responda em português brasileiro.
  Priorize segurança e conformidade em todas as orientações.

# CONTEXT & KNOWLEDGE SETTINGS
context:
  # CONTEXT SETTINGS
  # context: {}                              # Optional - Custom context data
  add_context: false                         # Default: False
  resolve_context: true                      # Default: True
  
  # KNOWLEDGE & RAG
  # knowledge: null                          # Optional - AgentKnowledge instance
  knowledge_filters:                         # Optional - Filter knowledge base
    business_unit: "PagBank"
    category: "banking"
  enable_agentic_knowledge_filters: false    # Default: False
  add_references: false                      # Default: False
  # retriever: null                          # Optional - Custom retriever
  references_format: "json"                  # Default: "json" | "yaml"

# MEMORY & HISTORY SETTINGS
memory:
  # MEMORY SETTINGS
  # memory: null                             # Optional - AgentMemory instance
  enable_agentic_memory: false               # Default: False
  enable_user_memories: false                # Default: False
  # add_memory_references: null              # Optional - Add memory refs to messages
  enable_session_summaries: false            # Default: False
  # add_session_summary_references: null     # Optional
  
  # HISTORY SETTINGS
  add_history_to_messages: true              # Default: False
  num_history_runs: 5                        # Default: 3
  # search_previous_sessions_history: false  # Optional - Default: False
  # num_history_sessions: null               # Optional

# STORAGE & DATA
storage:
  # STORAGE CONFIGURATION
  type: "postgres"                           # "postgres" | "sqlite" | "mongodb" | "yaml"
  table_name: "pagbank_specialist"           # REQUIRED for most storage types (no version)
  # schema: "ai"                             # Optional - PostgreSQL schema (default: "ai")
  # db_url: "${DATABASE_URL}"                # Required for postgres if no db_engine
  # db_engine: null                          # Optional - Existing SQLAlchemy engine
  schema_version: 1                          # Default: 1
  auto_upgrade_schema: true                  # Default: False
  mode: "agent"                              # Default: "agent" | "team" | "workflow"

# extra_data: {}                             # Optional - Additional data

# TOOL CONFIGURATION
tools:
  # TOOL LIST
  tools:                                     # Optional - List of tools
    - "search_knowledge_base"
    - "check_account_status"
    - "verify_transaction_limits"
  
  # TOOL SETTINGS
  show_tool_calls: true                      # Default: True
  # tool_call_limit: null                    # Optional - Limit number of tool calls
  # tool_choice: "auto"                      # Default: "auto" if tools, "none" if no tools
  # tool_hooks: []                           # Optional - Tool hook functions
  
  # DEFAULT TOOLS (Built-in)
  read_chat_history: false                   # Default: False - Add tool to read history
  search_knowledge: true                     # Default: True (only if knowledge provided)
  update_knowledge: false                    # Default: False - Add tool to update knowledge
  read_tool_call_history: false              # Default: False - Add tool to get tool history

# REASONING SETTINGS
reasoning:
  reasoning: false                           # Default: False
  # reasoning_model: null                    # Optional - Separate model for reasoning
  # reasoning_agent: null                    # Optional - Separate agent for reasoning
  reasoning_min_steps: 1                     # Default: 1
  reasoning_max_steps: 10                    # Default: 10

# RESPONSE & RETRY SETTINGS
response:
  # RESPONSE PARSING
  # response_model: null                     # Optional - Pydantic model for response
  parse_response: true                       # Default: True
  use_json_mode: false                       # Default: False
  # parser_model: null                       # Optional - Model for parsing
  # parser_model_prompt: null                # Optional
  
  # RETRY MECHANISM
  retries: 0                                 # Default: 0
  delay_between_retries: 1                   # Default: 1
  exponential_backoff: false                 # Default: False
  
  # OUTPUT HANDLING
  # save_response_to_file: null              # Optional - Save responses to file

# DEBUG & MONITORING
debug:
  debug_mode: false                          # Default: False
  
  # Note: monitoring and telemetry are controlled by environment variables:
  # AGNO_MONITOR="true" enables monitoring
  # AGNO_TELEMETRY="true" enables telemetry

# BUSINESS LOGIC (Custom - not Agno parameters)
business_logic:
  escalation_triggers:
    high_value_threshold: 5000               # R$ 5,000 for transfers
    security_keywords:
      - "bloqueio por segurança"
      - "transação bloqueada"
      - "pix bloqueado"
  
  suggested_actions:
    pix:
      - "check_pix_limits"
      - "view_pix_keys"
    transfer:
      - "check_transfer_limits"
      - "view_transfer_schedule"