# PagBank Digital Banking Agent Configuration
# Extracted from existing agents/specialists/pagbank_agent.py

agent:
  agent_id: "pagbank-specialist"
  version: 28
  name: "Especialista em Conta Digital PagBank"
  role: "Especialista em Conta Digital PagBank"
  description: "Especialista em PIX, transferências, folha de pagamento e serviços bancários digitais"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.7
  max_tokens: 2000

# Portuguese instructions for customer interactions
instructions: |
  Você é especialista em produtos e serviços digitais PagBank.
  
  Suas áreas de expertise incluem:
  - PIX: transferências instantâneas, chaves PIX, limites
  - Transferências: TED, DOC, limites e horários
  - Folha de pagamento: processamento, status, problemas
  - Aplicativo: funcionalidades, problemas técnicos, atualizações
  - Tarifas: consulta de tarifas, isenções, regras
  - Recarga de celular: operadoras, valores, favoritos
  - Portabilidade salarial: status, documentação
  
  Monitore especialmente:
  - Transferências acima de R$ 5.000 (escalação automática)
  - Bloqueios de segurança (investigação necessária)
  - Problemas na folha de pagamento (impacto empresarial)
  - Erros críticos no aplicativo (experiência do usuário)
  
  Sempre responda em português brasileiro.
  Priorize segurança e conformidade em todas as orientações.

# Knowledge base filtering and search configuration
knowledge_filter:
  business_unit: "PagBank"
  max_results: 5
  relevance_threshold: 0.3
  csv_file_path: "context/knowledge/knowledge_rag.csv"
  search_config:
    enable_hybrid_search: true
    use_semantic_search: true
    include_metadata: true

# Tools available to this agent
tools:
  - "search_knowledge_base"
  - "check_account_status"
  - "verify_transaction_limits"

# Storage configuration
storage:
  type: "postgres"
  table_name: "pagbank_specialist"
  auto_upgrade_schema: true

# Memory and history settings
memory:
  add_history_to_messages: true
  num_history_runs: 5

# Display settings
markdown: false
show_tool_calls: true

# Business logic for escalation (extracted from existing code)
escalation_triggers:
  high_value_threshold: 5000  # R$ 5,000 for transfers
  security_keywords:
    - "bloqueio por segurança"
    - "transação bloqueada"
    - "pix bloqueado"
    - "transferência negada"
    - "suspeita de fraude"
    - "conta bloqueada"
  payroll_keywords:
    - "folha não processada"
    - "erro na folha"
    - "pagamento não realizado"
    - "funcionários não receberam"
    - "folha rejeitada"
  app_critical_keywords:
    - "app não abre"
    - "tela branca"
    - "erro crítico"
    - "perdeu dados"
    - "não consigo acessar"
    - "travado"
    - "fechando sozinho"

# Suggested actions by query type
suggested_actions:
  pix:
    - "check_pix_limits"
    - "view_pix_keys"
    - "register_pix_key"
  transfer:
    - "check_transfer_limits"
    - "view_transfer_schedule"
  payroll:
    - "access_payroll_portal"
    - "check_payroll_status"
  app:
    - "update_app_version"
    - "clear_app_cache"
  fees:
    - "view_fee_schedule"
    - "check_fee_exemption_criteria"
  mobile_topup:
    - "access_mobile_topup"
    - "view_favorite_topups"