team:
  mode: route
  name: Ana - Atendimento PagBank personalizado
  team_id: ana
  version: dev
  description: Ana, assistente virtual empática do PagBank que ajuda com carinho e
    usa especialistas internamente
model:
  id: claude-sonnet-4-20250514
  provider: anthropic
  thinking:
    type: enabled
    budget_tokens: 1024
  max_tokens: 2000
  temperature: 1.0
events:
  store_events: true
  events_to_skip: []
memory:
  num_history_runs: 10
  enable_user_memories: true
  enable_agentic_memory: false
  add_history_to_messages: true
  enable_session_summaries: true
context:
  add_state_in_messages: true
  enable_agentic_context: true
  share_member_interactions: true
display:
  markdown: false
  show_tool_calls: true
  add_datetime_to_instructions: true
  add_member_tools_to_system_message: false
members:
- pagbank
- emissao
- adquirencia
- human-handoff
- finalizacao
storage:
  type: postgres
  table_name: teams_ana
  auto_upgrade_schema: true
streaming:
  stream: true
  stream_member_events: true
  show_members_responses: true
  stream_intermediate_steps: true
instructions: '🎯 Ana = ROTEAMENTO SILENCIOSO. Você é um proxy transparente.


  IMPORTANTE: Você tem acesso aos dados do usuário através do structured input UserContext:

  - Nome: {user_context.pb_user_name}

  - Telefone: {user_context.pb_phone_number}

  - CPF: {user_context.pb_user_cpf}

  - ID: {user_context.user_id}


  PADRÃO DE ROTEAMENTO:

  1. PIX/conta/saldo → forward_task_to_member("pagbank")

  2. Cartão/Crédito/Débito/limite/fatura → forward_task_to_member("emissao")

  3. Máquina/antecipação → forward_task_to_member("adquirencia")

  4. Humano/frustração → forward_task_to_member("human-handoff")

  5. Cliente finalizado/terminado/resolvido ("acabou", "terminei", "já consegui",
  "está resolvido", "finalizei") → forward_task_to_member("finalizacao")

  6. Chit chat/conversa casual → Ana pode conversar naturalmente


  🚫 PROIBIDO: Qualquer mensagem de confirmação, explicações, textos (EXCETO final
  de atendimento e chit chat)

  ✅ PERMITIDO: Apenas forward_task_to_member() - SEM texto adicional (EXCETO final
  de atendimento e chit chat)


  RESPOSTA: APENAS forward_task_to_member() - ZERO palavras para o usuário (EXCETO
  final de atendimento e chit chat)

  '
expected_output: 'RESPOSTA: forward_task_to_member() SEM NENHUMA mensagem para o usuário.
  (EXCETO final de atendimento e chit chat)'
success_criteria: SUCESSO = Ana disse MÁXIMO 15 palavras + chamou forward_task_to_member.
  Ana NÃO explicou NADA.
