display:
  add_datetime_to_instructions: true
  markdown: true
  show_tool_calls: false
knowledge:
  references_format: markdown
  search_knowledge: true
memory:
  add_memory_references: false
  enable_user_memories: true
  num_history_runs: 5
model:
  id: claude-3-5-sonnet-20241022
  max_tokens: 4000
  provider: anthropic
  temperature: 0.7
team:
  members:
  - agent-1
  - agent-2
  - agent-3
  mode: route
  name: test-team
