# Conversation Typification Workflow Configuration
# Following Agno framework standards for clean workflow organization

workflow:
  workflow_id: conversation-typification
  name: "Tipificação Automática de Atendimento"
  description: "Análise hierárquica da conversa seguindo padrão PagBank de 5 níveis"
  version: 35

# Model configurations for each agent step
models:
  default:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.1
    max_tokens: 500
  
  business_unit_classifier:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.1
    max_tokens: 300
  
  product_classifier:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.1
    max_tokens: 300
  
  motive_classifier:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.1
    max_tokens: 400
  
  submotive_classifier:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.1
    max_tokens: 500

# Storage configuration
storage:
  type: postgres
  table_name: conversation_typification_workflows
  mode: workflow
  auto_upgrade_schema: true

# Workflow execution settings
execution:
  timeout_seconds: 180
  max_retries: 2
  retry_delay_seconds: 1
  sequential_execution: true
  enable_structured_outputs: true

# Validation settings
validation:
  enable_hierarchy_validation: true
  hierarchy_file: "hierarchy.json"
  min_confidence_threshold: 0.7
  enable_quality_checks: true

# Business logic configuration
business_rules:
  team_routing:
    "Adquirência Web": "adquirencia_team"
    "Adquirência Web / Adquirência Presencial": "adquirencia_team"
    "Emissão": "emissao_team"
    "PagBank": "pagbank_team"
  
  priority_mapping:
    high_priority_keywords:
      - "bloqueio"
      - "fraude"
      - "perda"
      - "roubo"
      - "urgente"
      - "problema crítico"
    
    medium_priority_keywords:
      - "dúvida"
      - "orientação"
      - "informação"
      - "como fazer"
      - "procedimento"
    
    low_priority_keywords:
      - "consulta"
      - "verificação"
      - "confirmação"

# Integration settings
integrations:
  ana_team: true
  ticket_system: true
  whatsapp_notifications: true
  
  escalation_rules:
    low_confidence_threshold: 0.7
    escalation_timeout_seconds: 300

# Monitoring and alerting
monitoring:
  enable_metrics: true
  track_confidence_scores: true
  track_resolution_time: true
  track_validation_failures: true
  
  alerts:
    low_confidence_threshold: 0.6
    high_resolution_time_threshold: 300
    validation_failure_threshold: 0.1

# Development settings
development:
  debug_mode: false
  enable_cache: false
  demo_mode: false