# Human Handoff Workflow Configuration
# Converted from agent to workflow for enhanced orchestration

workflow:
  workflow_id: "human-handoff"
  name: "Human Handoff Workflow"
  description: "Orchestrates escalation to human agents with context preservation and notifications"
  version: 1

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.8
  max_tokens: 2000

# Escalation criteria and triggers
escalation_detection:
  frustration_indicators:
    - "droga"
    - "merda" 
    - "porra"
    - "caralho"
    - "desgraça"
    - "bosta"
    - "inferno"
    - "puta"
    - "cacete"
    - "foda"
  
  explicit_requests:
    - "quero falar com humano"
    - "quero atendente"
    - "falar com pessoa"
    - "atendimento humano"
    - "me transfere"
    - "pessoa real"
    - "não quero robô"
    - "chega de robô"
    - "preciso de supervisor"
    - "quero falar com gerente"
  
  caps_threshold: 0.7  # 70% caps = yelling
  
  high_value_threshold: 10000  # R$ 10,000+
  
  complexity_indicators:
    - "fraude"
    - "segurança"
    - "investigação"
    - "disputa"
    - "chargeback"
    - "processo"
    - "advogado"

# Protocol generation fields
protocol_fields:
  required:
    - customer_name
    - customer_cpf
    - issue_description
    - escalation_reason
  optional:
    - previous_attempts
    - urgency_level
    - customer_emotion
    - recommended_action
    - value_involved
    - conversation_summary

# WhatsApp notification settings
whatsapp:
  enabled: true
  instance: "SofIA"
  notification_template: |
    🚨 *Escalação para Atendimento Humano*
    
    📋 *Protocolo:* {protocol_id}
    👤 *Cliente:* {customer_name}
    📱 *CPF:* {customer_cpf}
    ⚠️ *Motivo:* {escalation_reason}
    🕐 *Horário:* {timestamp}
    
    📝 *Descrição:*
    {issue_description}
    
    💬 *Resumo da Conversa:*
    {conversation_summary}
    
    🎯 *Ação Recomendada:*
    {recommended_action}

# Team routing based on issue type
team_routing:
  adquirencia:
    - "antecipação"
    - "máquina"
    - "vendas"
    - "recebimento"
  emissao:
    - "cartão"
    - "limite"
    - "fatura"
    - "bloqueio"
  pagbank:
    - "pix"
    - "conta"
    - "aplicativo"
    - "transferência"
  general:
    - "fraude"
    - "segurança"
    - "disputa"

# Notification targets by team
notification_targets:
  adquirencia: "+5511999999001"
  emissao: "+5511999999002"  
  pagbank: "+5511999999003"
  general: "+5511999999000"  # Supervisor

# Storage configuration
storage:
  type: "postgres"
  table_name: "human_handoff_workflows"
  mode: "workflow"
  auto_upgrade_schema: true

# Workflow behavior
workflow_settings:
  timeout_minutes: 30
  retry_attempts: 3
  enable_context_preservation: true
  generate_handoff_report: true
  notify_completion: true