workflow:
  workflow_id: human-handoff
  name: Human Handoff Workflow
  description: Simplified escalation workflow for Ana team handoffs
  version: 33
model:
  provider: anthropic
  id: claude-sonnet-4-20250514
  temperature: 0.8
  max_tokens: 2000
whatsapp:
  enabled: true
  instance: SofIA
  notification_template: '🚨 *Escalação para Atendimento Humano*


    📋 *Protocolo:* {protocol_id}

    👤 *Cliente:* {customer_name}

    📱 *CPF:* {customer_cpf}

    ⚠️ *Motivo:* {escalation_reason}

    🕐 *Horário:* {timestamp}


    📝 *Descrição:* {issue_description}

    💬 *Resumo:* {conversation_summary}

    🎯 *Ação:* {recommended_action}

    '
storage:
  type: postgres
  table_name: human_handoff_workflows
  mode: workflow
  auto_upgrade_schema: true
workflow_settings:
  timeout_minutes: 30
  enable_context_preservation: true
  notify_completion: true
