# Human Handoff Agent Configuration
# Extracted from existing agents/specialists/human_handoff_agent.py

agent:
  agent_id: "human-handoff-specialist"
  version: 27
  name: "Especialista em Transferência Humana"
  role: "Especialista em Transferência Humana"
  description: "Especialista em escalação para atendimento humano e gestão de frustrações"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.8
  max_tokens: 1500

# Portuguese instructions for escalation management
instructions: |
  🎯 Você é especialista em escalação para atendimento humano do PagBank.
  
  QUANDO RECEBER UMA SOLICITAÇÃO DE ESCALAÇÃO:
  1. Use IMEDIATAMENTE a ferramenta trigger_human_handoff_workflow
  2. Passe toda informação disponível: mensagem do cliente, histórico, motivo
  3. A ferramenta executará o workflow completo e retornará o protocolo
  4. Repasse essa informação ao cliente
  
  PARÂMETROS PARA trigger_human_handoff_workflow:
  - customer_message: mensagem atual do cliente
  - escalation_reason: "explicit_request" ou "frustration_detected" 
  - conversation_history: todo o histórico da conversa
  - urgency_level: "medium" (padrão) ou "high" se urgente
  
  IMPORTANTE:
  - Use a ferramenta SEMPRE que houver escalação
  - A ferramenta usa external_execution=True, então pausa o agente
  - Aguarde o resultado da ferramenta e repasse ao cliente
  - Seja empático e profissional
  
  Sempre responda em português brasileiro.

# Knowledge base filtering
knowledge_filter:
  business_unit: "Human Handoff"

# Tools available to this agent
tools:
  - "trigger_human_handoff_workflow"

# Storage configuration
storage:
  type: "postgres"
  table_name: "human_handoff_specialist"
  auto_upgrade_schema: true

# Memory and history settings
memory:
  add_history_to_messages: true
  num_history_runs: 10  # More history for better context

# Display settings
markdown: false
show_tool_calls: true

# CRITICAL: Specialist response constraints (to prevent verbose responses)
success_criteria: "SUCESSO = Processou transferência humana de forma empática e eficiente em máximo 200 palavras"
expected_output: "Resposta concisa e empática com: 1) Confirmação da transferência, 2) Protocolo gerado, 3) Expectativas claras. EVITAR textos longos desnecessários."

# Escalation criteria (from human_handoff_detector.py)
escalation_triggers:
  frustration_indicators:
    - "droga"
    - "merda" 
    - "porra"
    - "caralho"
    - "desgraça"
    - "bosta"
    - "inferno"
    - "puta"
    - "cacete"
    - "foda"
  explicit_requests:
    - "quero falar com humano"
    - "quero atendente"
    - "falar com pessoa"
    - "atendimento humano"
    - "me transfere"
    - "pessoa real"
    - "não quero robô"
    - "chega de robô"
  caps_threshold: 0.7  # 70% caps = yelling
  
# Protocol generation
protocol_fields:
  - "customer_name"
  - "customer_cpf"
  - "issue_description"
  - "previous_attempts"
  - "urgency_level"
  - "customer_emotion"
  - "recommended_action"

# WhatsApp integration
# Now handled by dedicated WhatsApp Notifier Agent
whatsapp:
  enabled: true
  instance: "pagbank_support"
  agent: "whatsapp-notifier"  # Dedicated MCP-enabled agent