agent:
  agent_id: agent-1
  name: Agent One
  role: Primary Agent
display:
  markdown: true
  show_tool_calls: true
memory:
  add_memory_references: false
  enable_user_memories: true
  num_history_runs: 3
model:
  provider: anthropic
  temperature: 0.9
