agent:
  name: Human Handoff Specialist
  role: Escalation and Human Handoff Agent
  version: 35
  agent_id: human-handoff-specialist
  description: Specialized agent for handling escalations and human handoff workflows
model:
  id: claude-sonnet-4-20250514
  provider: anthropic
  max_tokens: 2000
  temperature: 0.8
storage:
  mode: workflow
  type: postgres
  table_name: human_handoff_workflows
  auto_upgrade_schema: true
whatsapp:
  enabled: true
  instance: SofIA
  notification_template: '🚨 *Escalação para Atendimento Humano*


    📋 *Protocolo:* {protocol_id}

    👤 *Cliente:* {customer_name}

    📱 *CPF:* {customer_cpf}

    ⚠️ *Motivo:* {escalation_reason}

    🕐 *Horário:* {timestamp}


    📝 *Descrição:* {issue_description}

    💬 *Resumo:* {conversation_summary}

    🎯 *Ação:* {recommended_action}

    '
workflow:
  name: Human Handoff Workflow
  version: 35
  description: Simplified escalation workflow for Ana team handoffs
  workflow_id: human-handoff
execution:
  max_retries: 2
  timeout_minutes: 30
  notify_completion: true
  retry_delay_seconds: 3
  enable_context_preservation: true
escalation:
  emotion_detection:
    angry_indicators:
    - indignado
    - revoltado
    - absurdo
    - inadmissível
    - péssimo
    urgent_indicators:
    - urgente
    - emergência
    - rápido
    - imediato
    - agora
    frustrated_indicators:
    - frustrado
    - chateado
    - irritado
    - não resolve
    - já tentei
  confidence_threshold: 0.8
monitoring:
  alerts:
    high_volume_threshold: 10
    failure_rate_threshold: 0.05
    response_time_threshold: 900
  enable_metrics: true
  track_response_times: true
  track_escalation_reasons: true
  track_resolution_success: true
development:
  demo_mode: false
  debug_mode: false
  enable_cache: false
integrations:
  ana_team: true
  ticket_system: true
  protocol_generator: true
  whatsapp_notifications: true
business_rules:
  team_routing:
    emissao: emissao_team
    general: general_team
    pagbank: pagbank_team
    adquirencia: adquirencia_team
  urgency_mapping:
    low_keywords:
    - consulta
    - verificação
    - confirmação
    high_keywords:
    - urgente
    - problema
    - não funciona
    - erro
    medium_keywords:
    - dúvida
    - ajuda
    - orientação
    - informação
    critical_keywords:
    - bloqueio
    - fraude
    - perda
    - roubo
    - crítico
