agent:
  name: "Template Example - Context-Aware Agent"
  role: "Personalized Assistant"
  version: 1
  agent_id: "template-agent"
  description: >
    Dynamic agent showcasing AGNO native context capabilities.
    Demonstrates context-aware personalization without complex templating.

model:
  id: claude-sonnet-4-20250514
  provider: anthropic
  max_tokens: 2000
  temperature: 0.1

# AGNO native context - automatically injected via context functions
add_context: true
resolve_context: true

memory:
  num_history_runs: 5
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true

storage:
  type: postgres
  table_name: agents_template_example
  auto_upgrade_schema: true

markdown: false

knowledge:
  search_knowledge: true
  valid_metadata_filters:
  - business_unit
  - solution
  - typification
  enable_agentic_knowledge_filters: true

instructions: |
  You are a demonstration agent showcasing AGNO native context capabilities.
  
  Your instructions will be dynamically enhanced with user context:
  - User information (name, email, phone, permissions)
  - Session details (session ID, channel, timestamp)
  - System context (environment, debug mode)
  - Organization details (tenant, subscription, features)
  
  Context is automatically available through AGNO's native context system.
  No templating required - context is resolved dynamically when needed.
  
  Guidelines:
  - Address users by name when context provides it
  - Adapt responses based on environment (more formal in production)
  - Consider user permissions for specialized advice
  - Provide detailed debugging information in debug mode
  - Use context to personalize responses appropriately

expected_output: |
  Context-aware personalized responses that adapt to user information,
  session details, and system environment without requiring templating.

show_tool_calls: false

knowledge_filter:
  max_results: 5
  search_config:
    include_metadata: true
    use_semantic_search: true
    enable_hybrid_search: true
  relevance_threshold: 0.7

success_criteria: >
  SUCESSO = Provided personalized assistance using AGNO native context
  with dynamic user-aware responses in current environment

suggested_actions:
  general:
  - get_help
  - contact_support
  - view_profile
  - update_preferences

escalation_triggers:
  error_keywords:
  - critical error
  - system failure
  - data loss

add_datetime_to_instructions: true

# Context configuration for AGNO native context
context_config:
  enable_user_context: true
  enable_session_context: true
  enable_system_context: true
  enable_tenant_context: true
  personalization_level: "standard"
  user_segment: "general"