# Template Workflow Configuration
# Following Agno framework standards for clean workflow organization

workflow:
  workflow_id: template
  name: "Template Workflow"
  description: "Template workflow demonstrating proper Agno Workflow configuration structure and parameters"
  version: 4

# Model configurations for workflow steps
models:
  default:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.7
    max_tokens: 2000
  
  analysis_step:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.3
    max_tokens: 1000
  
  synthesis_step:
    provider: anthropic
    id: claude-sonnet-4-20250514
    temperature: 0.8
    max_tokens: 1500

# Storage configuration
storage:
  type: postgres
  table_name: template_workflows
  mode: workflow
  auto_upgrade_schema: true

# Workflow execution settings
execution:
  timeout_seconds: 120
  max_retries: 2
  retry_delay_seconds: 1
  sequential_execution: true
  enable_structured_outputs: true

# Validation settings
validation:
  min_confidence_threshold: 0.7
  enable_quality_checks: true

# Integration settings
integrations:
  enable_notifications: false
  enable_external_apis: false
  
  escalation_rules:
    low_confidence_threshold: 0.6
    escalation_timeout_seconds: 180

# Monitoring and alerting
monitoring:
  enable_metrics: true
  track_confidence_scores: true
  track_resolution_time: true
  track_validation_failures: true
  
  alerts:
    low_confidence_threshold: 0.5
    high_resolution_time_threshold: 180
    validation_failure_threshold: 0.2

# Development settings
development:
  debug_mode: false
  enable_cache: true
  demo_mode: false