agent:
  name: "Ana - Adquirencia"
  role: "Assistente Digital Adquirência"
  version: 37
  agent_id: "adquirencia"
  description: "Ana, sua assistente digital especializada em antecipação de vendas do PagBank e multiadquirência"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 0.1
  max_tokens: 2000
  thinking:
    type: "enabled"
    budget_tokens: 1024

memory:
  enable_user_memories: true
  enable_agentic_memory: false
  add_history_to_messages: true
  num_history_runs: 10
  enable_session_summaries: true

storage:
  table_name: "agents_adquirencia"
  auto_upgrade_schema: true
  mode: "agent"

streaming:
  enable_streaming: true
  stream_intermediate_steps: true
  stream_tool_calls: true

events:
  enable_events: true
  event_types:
    - "agent_start"
    - "agent_end"
    - "tool_call"
    - "memory_update"

context:
  enable_context_sharing: true
  context_window: 4000

display:
  markdown: false
  show_tool_calls: true

knowledge:
  search_knowledge: true
  enable_agentic_knowledge_filters: true
  valid_metadata_filters:
    - "business_unit"
    - "solution"
    - "typification"
instructions: |
  Você é Ana, assistente virtual especializada em Adquirência do PagBank.
  
  Suas especialidades incluem:
  - Antecipação de vendas (elegibilidade, taxas, prazos)
  - Multiadquirência (múltiplas instituições, conciliação)
  - Taxas e tarifas (estrutura de custos, negociação)
  - Elegibilidade (critérios, documentação, aprovação)
  - Problemas operacionais (bloqueios, inconsistências)
  
  Diretrizes importantes:
  - Responda sempre em português brasileiro
  - Seja objetiva e prática nas soluções
  - Verifique antecipações acima de R$ 10.000
  - Investigue bloqueios de antecipação
  - Monitore suspeitas de fraude
  
  Dados do usuário disponíveis: {user_context.user_name}, {user_context.phone_number}, {user_context.cpf}
expected_output: |
  Resposta concisa e prática com:
  1) Solução direta
  2) Passos específicos
  3) Informações essenciais apenas
  EVITAR textos longos desnecessários.

success_criteria: |
  SUCESSO = Forneceu solução prática e objetiva para antecipação/vendas/adquirência em máximo 300 palavras

knowledge_filter:
  max_results: 3
  business_unit: "Adquirência Web"
  csv_file_path: "lib/knowledge/knowledge_rag.csv"
  relevance_threshold: 0.7
  search_config:
    include_metadata: true
    use_semantic_search: true
    enable_hybrid_search: true

suggested_actions:
  fees:
    - "calculate_anticipation_fees"
  anticipation:
    - "check_anticipation_eligibility"
    - "view_available_sales_for_anticipation"
  multi_acquiring:
    - "register_other_acquiring_machines"

escalation_triggers:
  high_value_threshold: 10000
  fraud_keywords:
    - "antecipação suspeita"
    - "valores incorretos"
    - "cobranças indevidas"
  blocked_keywords:
    - "não consigo antecipar"
    - "antecipação bloqueada"
    - "não aparece opção"
    - "sem elegibilidade"
    - "não elegível"

add_datetime_to_instructions: true
