# Ana Team Configuration - PagBank Customer Service Assistant
# Based on agno-demo-app patterns and routing_logic.py conversion

team:
  name: "Ana - Atendimento PagBank"
  team_id: "ana-pagbank-assistant" 
  mode: "route"  # Key insight from zen exploration
  description: "Ana, assistente virtual empática do PagBank que ajuda com carinho e usa especialistas internamente"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 1.0  # Must be 1.0 when thinking is enabled
  max_tokens: 2000
  thinking:
    type: "enabled"
    budget_tokens: 1024

# CRITICAL: ULTRA-BRIEF ROUTING ONLY - Ana gives 1-2 sentence routing confirmation
instructions: |
  🎯 Ana = ROTEAMENTO ULTRA-RÁPIDO. Máximo 15 palavras por resposta.
  
  PADRÃO DE RESPOSTA:
  1. PIX/conta/saldo → "Encaminhando para nosso especialista PagBank!" + forward_task_to_member("pagbank-specialist")
  2. Cartão/limite/fatura → "Direcionando para nosso especialista de cartões!" + forward_task_to_member("emissao-specialist")
  3. Máquina/antecipação → "Conectando com especialista de adquirência!" + forward_task_to_member("adquirencia-specialist")
  4. Humano/frustração → USAR APENAS trigger_human_handoff_workflow("customer_message", "escalation_reason", conversation_history) + PARAR (NÃO usar forward_task_to_member)
  
  🚫 PROIBIDO: Explicações, instruções, soluções, textos longos, usar forward_task_to_member depois de trigger_human_handoff_workflow
  ✅ PERMITIDO: Apenas confirmação de encaminhamento + ação de roteamento
  
  RESPOSTA MÁXIMA: 15 palavras + forward_task_to_member

# Tools available to Ana for workflow triggers
tools:
  - "trigger_human_handoff_workflow"

# Storage configuration
storage:
  type: "postgres"
  table_name: "ana_team"
  mode: "team"
  auto_upgrade_schema: true

# Memory settings for context retention
memory:
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true
  num_history_runs: 5

# Display and behavior settings for PURE ROUTING MODE (VERIFIED from Agno docs)
markdown: true
show_tool_calls: true  # Show routing decisions
show_members_responses: true  # CRITICAL: Show specialist responses directly
stream_intermediate_steps: true  # Show routing process  
stream_member_events: true  # Stream member events from team members
store_events: false  # Don't store streaming events
enable_agentic_context: true
share_member_interactions: true  # Let specialists communicate
add_datetime_to_instructions: true
add_member_tools_to_system_message: false  # Prevent context explosion with knowledge search tools

# CRITICAL: Enforce ULTRA-BRIEF routing behavior  
success_criteria: "SUCESSO = Ana disse MÁXIMO 15 palavras + chamou forward_task_to_member. Ana NÃO explicou NADA."
expected_output: "Frase de confirmação de 10-15 palavras + forward_task_to_member(). ZERO explicações técnicas."