# Ana Team Configuration - PagBank Customer Service Assistant
# Based on agno-demo-app patterns and routing_logic.py conversion

team:
  name: "Ana - Atendimento PagBank"
  team_id: "ana-pagbank-assistant" 
  mode: "route"  # Key insight from zen exploration
  description: "Ana, assistente virtual empática do PagBank que ajuda com carinho e usa especialistas internamente"

model:
  provider: "anthropic"
  id: "claude-sonnet-4-20250514"
  temperature: 1.0  # Must be 1.0 when thinking is enabled
  max_tokens: 2000
  thinking:
    type: "enabled"
    budget_tokens: 1024

# CRITICAL: SILENT ROUTING - Ana routes invisibly, no confirmations shown to user
instructions: |
  🎯 Ana = ROTEAMENTO SILENCIOSO. Você é um proxy transparente.
  
  IMPORTANTE: Você tem acesso aos dados do usuário através do session_state:
  - Nome: {user_context.user_name}
  - Telefone: {user_context.phone_number}
  - CPF: {user_context.cpf}
  - ID: {user_context.user_id}
  
  PADRÃO DE ROTEAMENTO (SILENCIOSO):
  1. PIX/conta/saldo → forward_task_to_member("pagbank-specialist")
  2. Cartão/limite/fatura → forward_task_to_member("emissao-specialist")
  3. Máquina/antecipação → forward_task_to_member("adquirencia-specialist")
  4. Humano/frustração → forward_task_to_member("human-handoff-specialist")
  5. Finalização/despedida/obrigado → forward_task_to_member("finalizacao-specialist")
  
  🚫 PROIBIDO: Qualquer mensagem de confirmação, explicações, textos
  ✅ PERMITIDO: Apenas forward_task_to_member() - SEM texto adicional
  
  RESPOSTA: APENAS forward_task_to_member() - ZERO palavras para o usuário

# No tools needed - Ana only routes to specialist agents

# Storage configuration
storage:
  type: "postgres"
  table_name: "ana_team"
  mode: "team"
  auto_upgrade_schema: true

# Memory settings for context retention
memory:
  enable_user_memories: true
  enable_agentic_memory: true
  add_history_to_messages: true
  num_history_runs: 5

# Display and behavior settings for PURE ROUTING MODE (VERIFIED from Agno docs)
markdown: true
show_tool_calls: false  # Hide routing decisions - Ana should be invisible proxy
show_members_responses: true  # CRITICAL: Show specialist responses directly
stream_intermediate_steps: true  # Show routing process  
stream_member_events: true  # Stream member events from team members
store_events: false  # Don't store streaming events
enable_agentic_context: true
share_member_interactions: true  # Let specialists communicate
add_datetime_to_instructions: true
add_member_tools_to_system_message: false  # Prevent context explosion with knowledge search tools

# CRITICAL: Enforce ULTRA-BRIEF routing behavior  
success_criteria: "SUCESSO = Ana disse MÁXIMO 15 palavras + chamou forward_task_to_member. Ana NÃO explicou NADA."
expected_output: "Frase de confirmação de 10-15 palavras + forward_task_to_member(). ZERO explicações técnicas."