# Template Team Configuration
# Comprehensive template showing all Agno Team parameters

team:
  team_id: template
  name: Complete Team Template
  description: Template demonstrating all Agno Team parameters
  version: 4
  mode: route

# Model configuration
model:
  provider: anthropic
  id: claude-sonnet-4-20250514
  temperature: 0.7
  max_tokens: 2000

# Team members
members:
  - template_example

# Storage configuration
storage:
  type: postgres
  table_name: template_teams
  auto_upgrade_schema: true

# Memory configuration
memory:
  num_history_runs: 10
  enable_user_memories: true
  enable_agentic_memory: false
  add_history_to_messages: true
  enable_session_summaries: true
  add_memory_references: true
  add_session_summary_references: true

# Display configuration
display:
  markdown: false
  show_tool_calls: true
  add_datetime_to_instructions: true

# Context configuration
context:
  add_state_in_messages: true
  enable_agentic_context: true
  share_member_interactions: true

# Events configuration
events:
  store_events: true
  events_to_skip: []

# Streaming configuration
streaming:
  stream: true
  stream_member_events: true
  show_members_responses: true
  stream_intermediate_steps: true

# Instructions
instructions: |
  You are a template team designed to demonstrate all Agno Team capabilities.
  
  Your primary functions:
  1. Route requests to appropriate team members
  2. Coordinate responses between multiple agents
  3. Maintain context across team interactions
  4. Demonstrate team-based AI workflows
  
  Always route requests to the most appropriate team member based on the request type.

# Expected output format
expected_output: |
  Professional team coordination with:
  1. Proper request routing
  2. Context sharing between members
  3. Coordinated responses
  4. Clear team workflow demonstration

# Success criteria
success_criteria: Successfully demonstrates all Agno Team parameters working together in a coordinated multi-agent workflow.